name: Rust

on:
  push:
    branches: [ "main", "feature/**" ]
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*"
  pull_request:
    branches: [ "main", "feature/**" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
        with:
          submodules: recursive
      - uses: dtolnay/rust-toolchain@stable
      - name: Set up system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config libvips-dev
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
